name: musicplayerandroid
description: "A new Flutter project."
publish_to: 'none'
objectbox:
  output_dir: database
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.1.1

  # objectbox
  objectbox: ^4.1.0
  objectbox_flutter_libs: any

  # deezer
  deezer: ^1.1.0

  # audio
  just_audio: ^0.9.42
  audio_service: ^0.18.16
  on_audio_query: ^2.9.0
  audiotags: ^1.4.0

  # utils
  file_picker: ^8.0.0+1
  file_saver: ^0.2.12
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  image: ^4.2.0

  # ui
  audio_video_progress_bar: ^2.0.2
  scrollable_positioned_list: ^0.3.5
  cupertino_icons: ^1.0.6
  bot_toast: ^4.1.3
  after_layout: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: FluentIcons-Resizable
      fonts:
        - asset: assets/fonts/FluentSystemIcons-Resizable.ttf